//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaKonfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zutaten
    {
        public int ZutatenID { get; set; }
        public Nullable<int> PizzaID { get; set; }
        public Nullable<int> ZutatenArtID { get; set; }
        public string Sort { get; set; }
        public Nullable<int> Menge { get; set; }
        public Nullable<decimal> Preis { get; set; }
    
        public virtual Pizza Pizza { get; set; }
        public virtual ZutatenArt ZutatenArt { get; set; }
    }
}
