//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaKonfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPizzaconfEntities : DbContext
    {
        public DbPizzaconfEntities()
            : base("name=DbPizzaconfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fisch> Fisches { get; set; }
        public virtual DbSet<Fleisch> Fleisches { get; set; }
        public virtual DbSet<Pizza> Pizzas { get; set; }
        public virtual DbSet<Pizzasoße> Pizzasoße { get; set; }
        public virtual DbSet<Rechnung> Rechnungs { get; set; }
        public virtual DbSet<Teig> Teigs { get; set; }
        public virtual DbSet<Vegetarische> Vegetarisches { get; set; }
        public virtual DbSet<Zutaten> Zutatens { get; set; }
        public virtual DbSet<ZutatenArt> ZutatenArts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
