//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaKonfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zutaten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zutaten()
        {
            this.Pizzas = new HashSet<Pizza>();
            this.Fisches = new HashSet<Fisch>();
            this.Fleisches = new HashSet<Fleisch>();
            this.Pizzasoße = new HashSet<Pizzasoße>();
            this.Teigs = new HashSet<Teig>();
            this.Vegetarisches = new HashSet<Vegetarische>();
        }
    
        public int ZutatenID { get; set; }
        public Nullable<int> PizzaID { get; set; }
        public Nullable<int> ZutatenArtID { get; set; }
        public string Sort { get; set; }
        public Nullable<int> Menge { get; set; }
        public Nullable<decimal> Preis { get; set; }
    
        public virtual Pizza Pizza { get; set; }
        public virtual ZutatenArt ZutatenArt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pizza> Pizzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fisch> Fisches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fleisch> Fleisches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pizzasoße> Pizzasoße { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teig> Teigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vegetarische> Vegetarisches { get; set; }
    }
}
